// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/chaos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartitionArgs struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockedPeerIds []string               `protobuf:"bytes,1,rep,name=blocked_peer_ids,json=blockedPeerIds,proto3" json:"blocked_peer_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartitionArgs) Reset() {
	*x = PartitionArgs{}
	mi := &file_proto_chaos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionArgs) ProtoMessage() {}

func (x *PartitionArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionArgs.ProtoReflect.Descriptor instead.
func (*PartitionArgs) Descriptor() ([]byte, []int) {
	return file_proto_chaos_proto_rawDescGZIP(), []int{0}
}

func (x *PartitionArgs) GetBlockedPeerIds() []string {
	if x != nil {
		return x.BlockedPeerIds
	}
	return nil
}

type DelayArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelayMs       int64                  `protobuf:"varint,1,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayArgs) Reset() {
	*x = DelayArgs{}
	mi := &file_proto_chaos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayArgs) ProtoMessage() {}

func (x *DelayArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayArgs.ProtoReflect.Descriptor instead.
func (*DelayArgs) Descriptor() ([]byte, []int) {
	return file_proto_chaos_proto_rawDescGZIP(), []int{1}
}

func (x *DelayArgs) GetDelayMs() int64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type ChaosAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaosAck) Reset() {
	*x = ChaosAck{}
	mi := &file_proto_chaos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaosAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaosAck) ProtoMessage() {}

func (x *ChaosAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaosAck.ProtoReflect.Descriptor instead.
func (*ChaosAck) Descriptor() ([]byte, []int) {
	return file_proto_chaos_proto_rawDescGZIP(), []int{2}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_chaos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaos_proto_rawDescGZIP(), []int{3}
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Term          uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,4,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	KnownLeaderId string                 `protobuf:"bytes,5,opt,name=known_leader_id,json=knownLeaderId,proto3" json:"known_leader_id,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,6,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_proto_chaos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_proto_chaos_proto_rawDescGZIP(), []int{4}
}

func (x *StatusReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusReply) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusReply) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusReply) GetKnownLeaderId() string {
	if x != nil {
		return x.KnownLeaderId
	}
	return ""
}

func (x *StatusReply) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

var File_proto_chaos_proto protoreflect.FileDescriptor

const file_proto_chaos_proto_rawDesc = "" +
	"\n" +
	"\x11proto/chaos.proto\x12\x04raft\"9\n" +
	"\rPartitionArgs\x12(\n" +
	"\x10blocked_peer_ids\x18\x01 \x03(\tR\x0eblockedPeerIds\"&\n" +
	"\tDelayArgs\x12\x19\n" +
	"\bdelay_ms\x18\x01 \x01(\x03R\adelayMs\"\n" +
	"\n" +
	"\bChaosAck\"\x0f\n" +
	"\rStatusRequest\"\xb8\x01\n" +
	"\vStatusReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12!\n" +
	"\fcommit_index\x18\x04 \x01(\x04R\vcommitIndex\x12&\n" +
	"\x0fknown_leader_id\x18\x05 \x01(\tR\rknownLeaderId\x12$\n" +
	"\x0elast_log_index\x18\x06 \x01(\x04R\flastLogIndex2\xa5\x01\n" +
	"\fChaosControl\x123\n" +
	"\fSetPartition\x12\x13.raft.PartitionArgs\x1a\x0e.raft.ChaosAck\x12+\n" +
	"\bSetDelay\x12\x0f.raft.DelayArgs\x1a\x0e.raft.ChaosAck\x123\n" +
	"\tGetStatus\x12\x13.raft.StatusRequest\x1a\x11.raft.StatusReplyB\x0eZ\fraftkv/protob\x06proto3"

var (
	file_proto_chaos_proto_rawDescOnce sync.Once
	file_proto_chaos_proto_rawDescData []byte
)

func file_proto_chaos_proto_rawDescGZIP() []byte {
	file_proto_chaos_proto_rawDescOnce.Do(func() {
		file_proto_chaos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chaos_proto_rawDesc), len(file_proto_chaos_proto_rawDesc)))
	})
	return file_proto_chaos_proto_rawDescData
}

var file_proto_chaos_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_chaos_proto_goTypes = []any{
	(*PartitionArgs)(nil), // 0: raft.PartitionArgs
	(*DelayArgs)(nil),     // 1: raft.DelayArgs
	(*ChaosAck)(nil),      // 2: raft.ChaosAck
	(*StatusRequest)(nil), // 3: raft.StatusRequest
	(*StatusReply)(nil),   // 4: raft.StatusReply
}
var file_proto_chaos_proto_depIdxs = []int32{
	0, // 0: raft.ChaosControl.SetPartition:input_type -> raft.PartitionArgs
	1, // 1: raft.ChaosControl.SetDelay:input_type -> raft.DelayArgs
	3, // 2: raft.ChaosControl.GetStatus:input_type -> raft.StatusRequest
	2, // 3: raft.ChaosControl.SetPartition:output_type -> raft.ChaosAck
	2, // 4: raft.ChaosControl.SetDelay:output_type -> raft.ChaosAck
	4, // 5: raft.ChaosControl.GetStatus:output_type -> raft.StatusReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chaos_proto_init() }
func file_proto_chaos_proto_init() {
	if File_proto_chaos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chaos_proto_rawDesc), len(file_proto_chaos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chaos_proto_goTypes,
		DependencyIndexes: file_proto_chaos_proto_depIdxs,
		MessageInfos:      file_proto_chaos_proto_msgTypes,
	}.Build()
	File_proto_chaos_proto = out.File
	file_proto_chaos_proto_goTypes = nil
	file_proto_chaos_proto_depIdxs = nil
}
