// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: proto/chaos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChaosControl_SetPartition_FullMethodName = "/raft.ChaosControl/SetPartition"
	ChaosControl_SetDelay_FullMethodName     = "/raft.ChaosControl/SetDelay"
	ChaosControl_GetStatus_FullMethodName    = "/raft.ChaosControl/GetStatus"
)

// ChaosControlClient is the client API for ChaosControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChaosControlClient interface {
	SetPartition(ctx context.Context, in *PartitionArgs, opts ...grpc.CallOption) (*ChaosAck, error)
	SetDelay(ctx context.Context, in *DelayArgs, opts ...grpc.CallOption) (*ChaosAck, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type chaosControlClient struct {
	cc grpc.ClientConnInterface
}

func NewChaosControlClient(cc grpc.ClientConnInterface) ChaosControlClient {
	return &chaosControlClient{cc}
}

func (c *chaosControlClient) SetPartition(ctx context.Context, in *PartitionArgs, opts ...grpc.CallOption) (*ChaosAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChaosAck)
	err := c.cc.Invoke(ctx, ChaosControl_SetPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosControlClient) SetDelay(ctx context.Context, in *DelayArgs, opts ...grpc.CallOption) (*ChaosAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChaosAck)
	err := c.cc.Invoke(ctx, ChaosControl_SetDelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosControlClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, ChaosControl_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChaosControlServer is the server API for ChaosControl service.
// All implementations must embed UnimplementedChaosControlServer
// for forward compatibility.
type ChaosControlServer interface {
	SetPartition(context.Context, *PartitionArgs) (*ChaosAck, error)
	SetDelay(context.Context, *DelayArgs) (*ChaosAck, error)
	GetStatus(context.Context, *StatusRequest) (*StatusReply, error)
	mustEmbedUnimplementedChaosControlServer()
}

// UnimplementedChaosControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChaosControlServer struct{}

func (UnimplementedChaosControlServer) SetPartition(context.Context, *PartitionArgs) (*ChaosAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPartition not implemented")
}
func (UnimplementedChaosControlServer) SetDelay(context.Context, *DelayArgs) (*ChaosAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDelay not implemented")
}
func (UnimplementedChaosControlServer) GetStatus(context.Context, *StatusRequest) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedChaosControlServer) mustEmbedUnimplementedChaosControlServer() {}
func (UnimplementedChaosControlServer) testEmbeddedByValue()                      {}

// UnsafeChaosControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChaosControlServer will
// result in compilation errors.
type UnsafeChaosControlServer interface {
	mustEmbedUnimplementedChaosControlServer()
}

func RegisterChaosControlServer(s grpc.ServiceRegistrar, srv ChaosControlServer) {
	// If the following call panics, it indicates UnimplementedChaosControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChaosControl_ServiceDesc, srv)
}

func _ChaosControl_SetPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosControlServer).SetPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChaosControl_SetPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosControlServer).SetPartition(ctx, req.(*PartitionArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosControl_SetDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelayArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosControlServer).SetDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChaosControl_SetDelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosControlServer).SetDelay(ctx, req.(*DelayArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosControl_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosControlServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChaosControl_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosControlServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChaosControl_ServiceDesc is the grpc.ServiceDesc for ChaosControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChaosControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.ChaosControl",
	HandlerType: (*ChaosControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPartition",
			Handler:    _ChaosControl_SetPartition_Handler,
		},
		{
			MethodName: "SetDelay",
			Handler:    _ChaosControl_SetDelay_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ChaosControl_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chaos.proto",
}
